### ISSUE TITLE
EPS rendering issues

### ISSUE THREAD

**Issue by timmolter** [eseifert/vectorgraphics2d#27] opened 2015-09-21 19:47 UTC
SVG and PDF are working perfectly. Hower for EPS, all the text is just off the image to the upper left. Any ideas what I could do to fix this?

See: https://github.com/timmolter/XChart/issues/105

**Comment by seifertm** [comment] 2015-09-22 10:01
Give me a quick reminder: Which version of VectorGrahpics2D are you using?

**Comment by timmolter** [comment] 2015-09-22 10:02
0.9.1

**Comment by seifertm** [comment] 2015-09-22 11:39
Thanks!

I could reproduce the issue by exporting AreaChart02 from the XChart demos. However, in the current git version of VectorGraphics2D, the problem seems to be fixed.

I will consult with @eseifert on whether we will backport the fix and do a 0.9.2 maintenance release or finally release 0.10.

**Comment by timmolter** [comment] 2015-09-22 11:40
Great!

**Comment by seifertm** [comment] 2015-09-26 10:20
We scheduled some further work on the API of the future 0.10 release, so there will be a 0.9.2 release containing the fix for the misplaced text in EPS files.

I expect 0.9.2 to be out today or tomorrow.

**Comment by seifertm** [comment] 2015-09-26 19:27
I just pushed a fix in the 0.9 branch. I have to do some more testing, but it seems to fix the problem with misaligned labels in EPS files. Release will follow.

**Comment by timmolter** [comment] 2015-09-27 18:26
Freue mich...

**Comment by eseifert** [comment] 2015-09-27 20:08
I just released VectorGraphics2D 0.9.2 which should fix the misaligned labels.

**Closed by eseifert** 2015-09-27 20:08 UTC

**Comment by timmolter** [comment] 2015-09-28 07:07
It works. Thanks a lot!
