### ISSUE TITLE
bad /BBox in font 'Dialog.plain'

### ISSUE THREAD

**Issue by ejabarov** [eseifert/vectorgraphics2d#66] opened 2018-04-12 06:02 UTC
Hello, 

Is there any way not to shows this warning in Acrobat Reader?

Thank you in advance

**Comment by eseifert** [comment] 2018-04-12 06:57
This bug is a duplicate of #41. Please continue the conversation there. Thanks.

**Closed by eseifert** 2018-04-12 06:57 UTC

**Comment by ejabarov** [comment] 2018-04-20 05:50
Thank you for your reply. Can you please provide some more information for the following case?

ProcessingPipeline g = null; g = new PDFGraphics2D(0, 0, 595, 842); chart.paint(g, view.getWidth(), view.getHeight()); try (FileOutputStream file = new FileOutputStream("test1.pdf")) { file.write(g.getBytes()); }
I am not really sure what font do you mean?

Thank you for your time
